[[headers]]
for = "/*"
[headers.values]
X-Content-Type-Options = "nosniff"
X-Frame-Options = "DENY"
Referrer-Policy = "strict-origin-when-cross-origin"
# Use one at a time:
Cache-Control = "public, max-age=0, must-revalidate"
Content-Security-Policy = """
  default-src 'self';

script-src
  'strict-dynamic' 'nonce-{nonce}' 'self' https:
  https://js.hcaptcha.com
  https://hcaptcha.com
  https://*.hcaptcha.com
  https://web3forms.com;          /* only if you use Web3Forms' optional uploader script */

style-src
  'self' 'unsafe-inline';

img-src
  'self' https: data: blob:
  https://hcaptcha.com
  https://*.hcaptcha.com;

font-src
  'self' https: data:;

connect-src
  'self'
  https://api.web3forms.com
  https://hcaptcha.com
  https://*.hcaptcha.com;

frame-src
  https://hcaptcha.com
  https://*.hcaptcha.com;

form-action
  'self' https://api.web3forms.com;

frame-ancestors 'none';
base-uri 'self';
object-src 'none';
upgrade-insecure-requests;
  """

[[headers]]
for = "/sitemap*.xml"
[headers.values]
Content-Type = "application/xml; charset=UTF-8"

[build]
command = "npm run build"
publish = "dist"
functions = "functions-serve"

[functions]
node_bundler = "esbuild"

[[headers]]
for = "/assets/*"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "/_astro/*"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "/fonts/*"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"
Access-Control-Allow-Origin = "*"

[[headers]]
for = "/favicon.ico"
[headers.values]
Cache-Control = "public, max-age=2592000"

[[headers]]
for = "/*.webp"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "/*.avif"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"
