[[headers]]
for = "/sitemap*.xml"
[headers.values]
Content-Type = "application/xml; charset=UTF-8"

[build]
command = "npm run build"
publish = "dist"
functions = "functions-serve"

[functions]
node_bundler = "esbuild"

[[headers]]
for = "/assets/*"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "/_astro/*"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "/fonts/*"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"
Access-Control-Allow-Origin = "*"

[[headers]]
for = "/favicon.ico"
[headers.values]
Cache-Control = "public, max-age=2592000"

[[headers]]
for = "/*.webp"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "/*.avif"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"
