media_folder: "src/assets/images" # Location where files will be stored in the repo
public_folder: "src/assets/images" # The src attribute for uploaded media

publish_mode: simple

collections:
  - name: "hero"
    label: "Hero Section"
    files:
      - label: "Hero Content"
        name: "hero"
        file: "src/content/hero/hero.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Main Title", name: "mainTitle", widget: "string" }
          - { label: "Subtitle", name: "subtitle", widget: "string" }
          - { label: "Description", name: "description", widget: "text" }
          - label: "Gallery Images"
            name: "images"
            widget: "list"
            fields:
              - { label: "Image", name: "image", widget: "image" }
              - { label: "Alt Text", name: "alt", widget: "string" }
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Description", name: "description", widget: "text" }

  - name: "italianToursGallery"
    label: "Italian Tours Gallery"
    files:
      - label: "Tours Gallery Content"
        name: "italianToursGallery"
        file: "src/content/italianToursGallery/italianToursGallery.md"
        fields:
          - label: "Tours"
            name: "tours"
            widget: "list"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - {
                  label: "Slug",
                  name: "slug",
                  widget: "string",
                  hint: "URL-friendly identifier (e.g., genoa-walking-tour)",
                }
              - { label: "Description", name: "description", widget: "text" }
              - {
                  label: "Categories",
                  name: "categories",
                  widget: "select",
                  multiple: true,
                  min: 1,
                  options: ["city", "coastal", "cultural", "history"],
                  default: ["city"],
                }
              - {
                  label: "Full Description",
                  name: "fullDescription",
                  widget: "text",
                }
              - label: "Key Points"
                name: "points"
                widget: "list"
                field: { label: "Point", name: "point", widget: "string" }
              - { label: "Duration", name: "duration", widget: "string" }
              - { label: "Price", name: "price", widget: "string" }
              - label: "Images"
                name: "images"
                widget: "list"
                fields:
                  - { label: "Image", name: "image", widget: "image" }
                  - { label: "Alt Text", name: "alt", widget: "string" }

backend:
  name: git-gateway
  repo: anisa07/liguria-tours
  branch: master
